/**
 * chapter-modules.js
 *
 * Provides canonical module ordering for OpenStax books.
 *
 * Primary source: collection-order.json (auto-generated by download-source.js
 * from the OpenStax collection.xml). Works for any book without hardcoded maps.
 *
 * Fallback: hardcoded CHEMISTRY_2E_MODULES map (legacy, kept for safety).
 */

import fs from 'fs';
import path from 'path';

const REPO_ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..');

// ---------------------------------------------------------------------------
// Collection-order.json reader (primary source, works for any book)
// ---------------------------------------------------------------------------

/**
 * Load module ordering from collection-order.json.
 * This file is generated by download-source.js from the OpenStax collection.xml.
 *
 * @param {string} bookSlug - Book identifier (e.g., 'edlisfraedi-2e')
 * @returns {object|null} Parsed collection structure, or null if not found
 */
function loadCollectionOrder(bookSlug) {
  const filePath = path.join(REPO_ROOT, 'books', bookSlug, '01-source', 'collection-order.json');
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

/**
 * Get all modules for a specific chapter in canonical order.
 *
 * Reads from collection-order.json (auto-generated by download-source.js).
 * Falls back to hardcoded chemistry map for backwards compatibility.
 *
 * @param {number} chapter - Chapter number
 * @param {string} [bookSlug] - Book identifier. Required for non-chemistry books.
 * @returns {Array<{moduleId: string, chapter: number, section: string, title: string}>}
 */
function getChapterModules(chapter, bookSlug) {
  const collection = bookSlug ? loadCollectionOrder(bookSlug) : null;
  if (!collection) {
    // Fail loud: no chemistry fallback. A book without collection-order.json
    // (or a forgotten --book) is a configuration error, not a chemistry default.
    throw new Error(
      `No collection-order.json for ${bookSlug || '(no --book)'} ` +
        '(books/<slug>/01-source/collection-order.json). A book must provide one.'
    );
  }

  const chapterData = collection.chapters.find((ch) => ch.chapter === chapter);
  if (!chapterData) return []; // valid book, but this chapter has no modules

  return chapterData.modules.map((moduleId, index) => ({
    moduleId,
    chapter,
    section: index === 0 ? 'intro' : `${chapter}.${index}`,
    title: chapterData.title,
  }));
}

export { getChapterModules };
