#!/usr/bin/env bash
#
# Automated git backup for content files edited via the web interface.
#
# Commits and pushes changes in content directories under books/ to GitHub.
# Designed to run as a cron job every 2 hours:
#   0 */2 * * * /path/to/namsbokasafn-efni/scripts/git-backup.sh
# (Run scripts/install-cron.sh to print the recommended crontab; override
#  the path with DEPLOY_PATH=... env var if your deploy lives elsewhere.)
#
# What gets backed up:
#   books/*/03-faithful-translation/  — reviewed translations
#   books/*/03-translated/            — injected CNXML
#   books/*/04-localized-content/     — localized content
#   books/*/04-localization/          — localization in progress
#   books/*/05-publication/           — rendered HTML
#   books/*/chapters/                 — status files
#   books/*/glossary/                 — MT-priming glossary export (see server/scripts/export-terminology.js)
#   books/*/translation-errors.json   — fidelity manifest (regenerated by inject)
#   books/*/residue-report.*.json     — EN-residue manifest (regenerated by inject)
#   books/*/02-mt-output/*/*-segments.locked  — MT edit-lock markers (see tools/lib/mt-lock.cjs)
#
# Logs to pipeline-output/backup.log (gitignored).
# Writes status to pipeline-output/backup-status.json (gitignored).
# Writes a heartbeat to pipeline-output/.last-content-backup on healthy runs
# only (gitignored) — read by server/lib/contentBackupHealth.js.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_FILE="${PROJECT_ROOT}/pipeline-output/backup.log"
STATUS_FILE="${PROJECT_ROOT}/pipeline-output/backup-status.json"
HEARTBEAT_FILE="${PROJECT_ROOT}/pipeline-output/.last-content-backup"
TIMESTAMP="$(date -u +%Y-%m-%d\ %H:%M)"

# Ensure pipeline-output directory exists
mkdir -p "${PROJECT_ROOT}/pipeline-output"

log() {
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >> "$LOG_FILE"
}

write_status() {
  local status="$1"
  local message="$2"
  cat > "$STATUS_FILE" <<EOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "status": "${status}",
  "message": "${message}"
}
EOF
}

# Heartbeat: written ONLY on a healthy terminal path — a successful push, or
# a run that found nothing to commit AND nothing unpushed. A run that failed
# to stage, commit or push must leave it untouched.
#
# Why not just read backup-status.json? That file is written on EVERY
# outcome, so once the cron stops entirely it keeps reading "success"
# forever. Inverting the signal makes absence the alarm. `no_changes` counts
# as healthy ONLY when nothing is unpushed: a quiet weekend is a working
# cron, and an alarm that cries wolf every weekend is not an alarm — but a
# quiet run sitting on top of a rejected push is exactly the failure this
# detector exists to catch, and it must not clear the alarm (see
# unpushed_backlog below).
#
# Consumed by GET /api/health — see server/lib/contentBackupHealth.js.
write_heartbeat() {
  date -u +%Y-%m-%dT%H:%M:%SZ > "$HEARTBEAT_FILE"
}

# How many commits exist here that origin/main does not have.
#
# `git push` updates refs/remotes/origin/main on success, so this is exact
# and needs NO network: 0 means everything committed by this cron has landed,
# and >0 means a previous run's push failed and its content is still only on
# this box. Echoes the count, or the empty string if it cannot be determined
# (no origin/main ref) — the caller treats indeterminate as unhealthy, since
# a detector must not report healthy about something it cannot see.
unpushed_backlog() {
  git rev-list --count origin/main..HEAD 2>/dev/null || true
}

cd "$PROJECT_ROOT"

# Verify we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  log "ERROR: Not a git repository: $PROJECT_ROOT"
  write_status "error" "Not a git repository"
  exit 1
fi

# Refresh each book's MT-priming glossary from the terminology DB before
# staging (register C14). The DB lives only on this box, and the
# books/*/glossary/ pathspec below is the ONLY channel by which it reaches
# the dev checkout where tools/api-translate.js primes Málstaður. Running
# the export here rather than from its own crontab entry means it needs no
# separate installation step on production.
#
# CONTAINED DELIBERATELY: this script is `set -euo pipefail` and its
# heartbeat is the content-backup alarm (register C11(b)). A terminology-DB
# problem must not abort the content backup or suppress that heartbeat, so a
# failure here logs a WARN and the run continues. The export has its OWN
# heartbeat and its own /api/health check (checks.glossary_export), so a
# persistent failure stays visible instead of being swallowed.
#
# PATH is pinned to /usr/bin exactly as scripts/deploy.sh does: cron has a
# minimal environment, and an nvm-shadowed `node` would load a
# better-sqlite3 built for a different NODE_MODULE_VERSION.
#
# ⚠️ Parked minor from the Task 6 per-task review, resolved 2026-07-28:
# scoped to a per-command PATH assignment instead of `export`. An exported
# PATH is a PERMANENT mutation for the rest of THIS script — it would still
# be in effect for every git/date/timeout call below, including the
# `git commit`/`git push`/`git fetch` further down, none of which need
# /usr/bin prioritized and none of which were exercised under it before this
# glossary-export block existed. deploy.sh pins PATH as its first executable
# line specifically because its whole script needs it; this script does not,
# so exporting here left the two use sites (`git`, further down, and `node`,
# here) able to silently drift onto two different resolution rules within
# one run. Applied to BOTH the existence check and the invocation below —
# not just the invocation — so a cron PATH minimal enough to omit /usr/bin
# entirely cannot make the existence check report a false "not found" while
# the (correctly /usr/bin-scoped) invocation would in fact have worked.
if PATH="/usr/bin:$PATH" command -v node > /dev/null 2>&1; then
  # ⚠️ `timeout` is not belt-and-braces. A HANG is the one failure the `if !`
  # wrapper cannot catch — it tests the exit status of a process that never
  # returns — and a hang blocks this script before write_heartbeat, which is
  # precisely the outcome the containment exists to prevent, arriving through
  # the one door the wrapper does not watch. The risk is concrete: this caller
  # opens sessions.db as a SECOND process while the live editorial server holds
  # it, so lock contention is a real possibility. There is also no flock here,
  # so a hung export would let the next 2h tick start a second
  # add/commit/push against the same working tree. 120s is far above the
  # ~2.3s a four-book run takes on this branch (measured 2026-08-09: 2,264 ms,
  # 136 MB RSS; it was sub-second before the resolved cut-over), and far below
  # the 2h cron period.
  if ! PATH="/usr/bin:$PATH" timeout 120 node "${PROJECT_ROOT}/server/scripts/export-terminology.js" \
       >> "$LOG_FILE" 2>&1; then
    log "WARN: glossary export ERRORED or timed out — continuing with the content backup (a per-book refusal is NOT an error and does not reach here; see checks.glossary_export)"
  fi
else
  log "WARN: node not found in cron PATH — glossary export skipped"
fi

# Stage content directories under books/, one pathspec at a time.
# translation-errors.json and residue-report.<track>.json are regenerated on
# every inject, so they are always dirty on the production server after a
# "Vista + Birta"; stage them here so they ride along with the backup commit
# instead of snagging the next `git pull`.
#
# Per-pattern staging (campaign item 4b): an unmatched glob is a legitimate
# state (fresh deploy without residue reports; every .locked marker
# reverted) — it logs a WARN and is skipped, and can no longer take the
# other pathspecs down with it (the old shared `git add … || true` exited
# 128 for the WHOLE command on one unmatched glob, silently staging
# nothing). A real `git add` failure (index lock, permissions) fails the
# run loudly instead of being suppressed.
PATHSPECS=(
  'books/*/03-faithful-translation/'
  'books/*/03-translated/'
  'books/*/04-localized-content/'
  'books/*/04-localization/'
  'books/*/05-publication/'
  'books/*/chapters/'
  'books/*/glossary/'
  'books/*/tm/'
  'books/*/translation-errors.json'
  'books/*/residue-report.*.json'
  'books/*/02-mt-output/*/*-segments.locked'
)

ADD_FAILURES=0
for pathspec in "${PATHSPECS[@]}"; do
  if compgen -G "$pathspec" > /dev/null; then
    # Drop matches git ignores before naming them. `git add` treats an
    # EXPLICITLY NAMED ignored path as a hard error and exits 1 — even though it
    # stages every other path in the same command — so one ignored match would
    # log ERROR, abort the run and skip the C11(b) heartbeat, turning a test
    # artifact into a false "content backup is broken" alarm. This is not
    # hypothetical: the E2E fixture book is COMMITTED while its test-written
    # output dirs are gitignored (.gitignore, "E2E fixture book" block), and
    # those dirs match these globs on any box that has run E2E.
    mapfile -t matches < <(compgen -G "$pathspec")
    staged=()
    for match in "${matches[@]}"; do
      if git check-ignore -q "$match"; then
        log "INFO: skipped gitignored path: $match"
      else
        staged+=("$match")
      fi
    done

    if [ ${#staged[@]} -eq 0 ]; then
      log "WARN: pathspec matched only gitignored paths (skipped): $pathspec"
    elif ! git add -- "${staged[@]}"; then
      log "ERROR: git add failed for pathspec: $pathspec"
      ADD_FAILURES=$((ADD_FAILURES + 1))
    fi
  else
    log "WARN: pathspec matched nothing (skipped): $pathspec"
  fi
done

if [ "$ADD_FAILURES" -gt 0 ]; then
  log "ERROR: ${ADD_FAILURES} pathspec(s) failed to stage — aborting backup run"
  write_status "error" "git add failed for ${ADD_FAILURES} pathspec(s)"
  exit 1
fi

# Check if there's anything to commit
if git diff --cached --quiet; then
  # Nothing new — but "nothing new" is only healthy if everything already
  # committed has actually reached origin. A run that quietly refreshed the
  # heartbeat here would clear the alarm two hours after a rejected push,
  # before the staleness threshold could ever fire.
  BACKLOG="$(unpushed_backlog)"
  if [ -z "$BACKLOG" ]; then
    log "ERROR: could not determine unpushed backlog (no origin/main ref)"
    write_status "error" "could not determine unpushed backlog"
    exit 1
  fi
  if [ "$BACKLOG" -gt 0 ]; then
    log "ERROR: unpushed backlog: ${BACKLOG} commit(s) not on origin/main"
    write_status "error" "unpushed backlog: ${BACKLOG} commit(s)"
    exit 1
  fi
  log "No changes to back up"
  write_status "no_changes" "Nothing to commit"
  write_heartbeat
  exit 0
fi

# Commit
if ! git commit -m "auto-backup: ${TIMESTAMP}"; then
  log "ERROR: git commit failed"
  write_status "error" "git commit failed"
  exit 1
fi

# Push
if ! git push origin main 2>&1 | tee -a "$LOG_FILE"; then
  PUSH_MSG="git push failed"
  # Read-only diagnosis, on the already-failed path only. It distinguishes
  # "GitHub unreachable" from "non-fast-forward — production has diverged",
  # which matters because this script deliberately never fetches before
  # pushing: `merge.ours.driver` for the perpetually-dirty
  # books/*/translation-errors.json is registered by deploy.sh, not by cron,
  # so an unattended rebase here would turn a visible push failure into a
  # repo wedged mid-rebase on production.
  #
  # `timeout` guards the likely case that the network is what failed. If the
  # fetch fails for any reason the counts are simply omitted — a diagnostic
  # must never turn one failure into a different one.
  if timeout 30 git fetch --quiet origin main 2>/dev/null; then
    AHEAD="$(git rev-list --count FETCH_HEAD..HEAD 2>/dev/null || true)"
    BEHIND="$(git rev-list --count HEAD..FETCH_HEAD 2>/dev/null || true)"
    if [ -n "$AHEAD" ] && [ -n "$BEHIND" ]; then
      PUSH_MSG="git push failed (local ahead ${AHEAD}, behind ${BEHIND})"
    fi
  fi
  log "ERROR: ${PUSH_MSG}"
  write_status "error" "${PUSH_MSG}"
  exit 1
fi

COMMIT_HASH="$(git rev-parse --short HEAD)"
log "Backup complete: ${COMMIT_HASH} (auto-backup: ${TIMESTAMP})"
write_status "success" "Pushed ${COMMIT_HASH}"
write_heartbeat
