#!/usr/bin/env bash
#
# Automated git backup for content files edited via the web interface.
#
# Commits and pushes changes in content directories under books/ to GitHub.
# Designed to run as a cron job every 2 hours:
#   0 */2 * * * /path/to/namsbokasafn-efni/scripts/git-backup.sh
# (Run scripts/install-cron.sh to print the recommended crontab; override
#  the path with DEPLOY_PATH=... env var if your deploy lives elsewhere.)
#
# What gets backed up:
#   books/*/03-faithful-translation/  — reviewed translations
#   books/*/03-translated/            — injected CNXML
#   books/*/04-localized-content/     — localized content
#   books/*/04-localization/          — localization in progress
#   books/*/05-publication/           — rendered HTML
#   books/*/chapters/                 — status files
#   books/*/translation-errors.json   — fidelity manifest (regenerated by inject)
#   books/*/residue-report.*.json     — EN-residue manifest (regenerated by inject)
#   books/*/02-mt-output/*/*-segments.locked  — MT edit-lock markers (see tools/lib/mt-lock.cjs)
#
# Logs to pipeline-output/backup.log (gitignored).
# Writes status to pipeline-output/backup-status.json (gitignored).
# Writes a heartbeat to pipeline-output/.last-content-backup on healthy runs
# only (gitignored) — read by server/lib/contentBackupHealth.js.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_FILE="${PROJECT_ROOT}/pipeline-output/backup.log"
STATUS_FILE="${PROJECT_ROOT}/pipeline-output/backup-status.json"
HEARTBEAT_FILE="${PROJECT_ROOT}/pipeline-output/.last-content-backup"
TIMESTAMP="$(date -u +%Y-%m-%d\ %H:%M)"

# Ensure pipeline-output directory exists
mkdir -p "${PROJECT_ROOT}/pipeline-output"

log() {
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >> "$LOG_FILE"
}

write_status() {
  local status="$1"
  local message="$2"
  cat > "$STATUS_FILE" <<EOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "status": "${status}",
  "message": "${message}"
}
EOF
}

# Heartbeat: written ONLY on a healthy terminal path — a successful push, or
# a run that found nothing to commit. A run that failed to stage, commit or
# push must leave it untouched.
#
# Why not just read backup-status.json? That file is written on EVERY
# outcome, so once the cron stops entirely it keeps reading "success"
# forever. Inverting the signal makes absence the alarm. `no_changes` counts
# as healthy on purpose: a quiet weekend is a working cron, and an alarm that
# cries wolf every weekend is not an alarm.
#
# Consumed by GET /api/health — see server/lib/contentBackupHealth.js.
write_heartbeat() {
  date -u +%Y-%m-%dT%H:%M:%SZ > "$HEARTBEAT_FILE"
}

cd "$PROJECT_ROOT"

# Verify we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  log "ERROR: Not a git repository: $PROJECT_ROOT"
  write_status "error" "Not a git repository"
  exit 1
fi

# Stage content directories under books/, one pathspec at a time.
# translation-errors.json and residue-report.<track>.json are regenerated on
# every inject, so they are always dirty on the production server after a
# "Vista + Birta"; stage them here so they ride along with the backup commit
# instead of snagging the next `git pull`.
#
# Per-pattern staging (campaign item 4b): an unmatched glob is a legitimate
# state (fresh deploy without residue reports; every .locked marker
# reverted) — it logs a WARN and is skipped, and can no longer take the
# other pathspecs down with it (the old shared `git add … || true` exited
# 128 for the WHOLE command on one unmatched glob, silently staging
# nothing). A real `git add` failure (index lock, permissions) fails the
# run loudly instead of being suppressed.
PATHSPECS=(
  'books/*/03-faithful-translation/'
  'books/*/03-translated/'
  'books/*/04-localized-content/'
  'books/*/04-localization/'
  'books/*/05-publication/'
  'books/*/chapters/'
  'books/*/translation-errors.json'
  'books/*/residue-report.*.json'
  'books/*/02-mt-output/*/*-segments.locked'
)

ADD_FAILURES=0
for pathspec in "${PATHSPECS[@]}"; do
  if compgen -G "$pathspec" > /dev/null; then
    # shellcheck disable=SC2086 # the glob must expand into git's arguments
    if ! git add -- $pathspec; then
      log "ERROR: git add failed for pathspec: $pathspec"
      ADD_FAILURES=$((ADD_FAILURES + 1))
    fi
  else
    log "WARN: pathspec matched nothing (skipped): $pathspec"
  fi
done

if [ "$ADD_FAILURES" -gt 0 ]; then
  log "ERROR: ${ADD_FAILURES} pathspec(s) failed to stage — aborting backup run"
  write_status "error" "git add failed for ${ADD_FAILURES} pathspec(s)"
  exit 1
fi

# Check if there's anything to commit
if git diff --cached --quiet; then
  log "No changes to back up"
  write_status "no_changes" "Nothing to commit"
  write_heartbeat
  exit 0
fi

# Commit
if ! git commit -m "auto-backup: ${TIMESTAMP}"; then
  log "ERROR: git commit failed"
  write_status "error" "git commit failed"
  exit 1
fi

# Push
if ! git push origin main 2>&1 | tee -a "$LOG_FILE"; then
  log "ERROR: git push failed"
  write_status "error" "git push failed"
  exit 1
fi

COMMIT_HASH="$(git rev-parse --short HEAD)"
log "Backup complete: ${COMMIT_HASH} (auto-backup: ${TIMESTAMP})"
write_status "success" "Pushed ${COMMIT_HASH}"
write_heartbeat
