/**
 * GENERATED by server/scripts/derive-case-fold.js — do not hand-edit.
 * Code points where JS simple case FOLDING (what /iu uses) disagrees with
 * lowercase MAPPING (what String#toLowerCase does).
 * Verified exhaustively by server/__tests__/caseFold.test.js.
 */
module.exports = [
  ['\u017F', '\u0073'],
  ['\u0399', '\u0345'],
  ['\u039C', '\u00B5'],
  ['\u03A3', '\u03C2'],
  ['\u03B9', '\u0345'],
  ['\u03BC', '\u00B5'],
  ['\u03C3', '\u03C2'],
  ['\u03D0', '\u03B2'],
  ['\u03D1', '\u03B8'],
  ['\u03D5', '\u03C6'],
  ['\u03D6', '\u03C0'],
  ['\u03F0', '\u03BA'],
  ['\u03F1', '\u03C1'],
  ['\u03F5', '\u03B5'],
  ['\u1C80', '\u0432'],
  ['\u1C81', '\u0434'],
  ['\u1C82', '\u043E'],
  ['\u1C83', '\u0441'],
  ['\u1C84', '\u0442'],
  ['\u1C85', '\u0442'],
  ['\u1C86', '\u044A'],
  ['\u1C87', '\u0463'],
  ['\u1E9B', '\u1E61'],
  ['\u1FBE', '\u0345'],
  ['\uA64A', '\u1C88'],
  ['\uA64B', '\u1C88'],
];
